# Generated by Django 3.1.1 on 2020-09-09 14:49

from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=50)),
                ('dol', models.DateField()),
                ('last_seen', models.TextField(max_length=300)),
                ('dob', models.DateField()),
                ('mobileno', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('current_user', models.CharField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, max_length=30, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
